brokerAddress: "127.0.0.1"
brokerPort: 1883
daProperties:
  - propertyKey: "intensity"
    topic: "sensor/intensity"
    type: "json-array"
    field-type: "int"
    initialValue:
    - 0
    - 4
  - propertyKey: "switch"
    topic: "device/switch"
    type: "string"
    initialValue: "OFF"
daActions:
  - actionKey: "switch-off"
    type: "sensor.actuation"
    contentType: "text/plain"
    topic: "sensor/actions/switch"
    action: "switch"
daEvents:
  - eventKey: "overheating"
    type: "text/plain"
    topic: "sensor/overheating"
