brokerAddress: "127.0.0.1"
brokerPort: 1883
daProperties:
  - propertyKey: "energy"
    topic: "dummy/properties/energy"
    type: "double"
    #field-type: "int"
    #initialValue:
    #- 0
    #- 4
  - propertyKey: "switch"
    topic: "dummy/properties/switch"
    type: "string"
    #initialValue: "OFF"
daActions:
  - actionKey: "switch-off"
    #type: "sensor.actuation"
    #contentType: "text/plain"
    topic: "app/actions/switch-off"
    #action: "switch"
daEvents:
  - eventKey: "overheating"
    #type: "text/plain"
    topic: "dummy/events/overheating/notifications"
